//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.regierung-mv.de/xprozess/2}Basisnachricht"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="exportprofil" type="{http://www.regierung-mv.de/xprozess/2}Suchprofil.AlleInhalte" minOccurs="0"/&gt;
 *         &lt;element name="prozesskatalog" type="{http://www.regierung-mv.de/xprozess/2}Prozesskatalog" minOccurs="0"/&gt;
 *         &lt;element name="prozessbibliothek" type="{http://www.regierung-mv.de/xprozess/2}Prozessbibliothek" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "exportprofil",
    "prozesskatalog",
    "prozessbibliothek"
})
@XmlRootElement(name = "alleInhalte.export.0303")
public class AlleInhalteExport0303
    extends Basisnachricht
{

    protected SuchprofilAlleInhalte exportprofil;
    protected Prozesskatalog prozesskatalog;
    protected Prozessbibliothek prozessbibliothek;

    /**
     * Gets the value of the exportprofil property.
     * 
     * @return
     *     possible object is
     *     {@link SuchprofilAlleInhalte }
     *     
     */
    public SuchprofilAlleInhalte getExportprofil() {
        return exportprofil;
    }

    /**
     * Sets the value of the exportprofil property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuchprofilAlleInhalte }
     *     
     */
    public void setExportprofil(SuchprofilAlleInhalte value) {
        this.exportprofil = value;
    }

    /**
     * Gets the value of the prozesskatalog property.
     * 
     * @return
     *     possible object is
     *     {@link Prozesskatalog }
     *     
     */
    public Prozesskatalog getProzesskatalog() {
        return prozesskatalog;
    }

    /**
     * Sets the value of the prozesskatalog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prozesskatalog }
     *     
     */
    public void setProzesskatalog(Prozesskatalog value) {
        this.prozesskatalog = value;
    }

    /**
     * Gets the value of the prozessbibliothek property.
     * 
     * @return
     *     possible object is
     *     {@link Prozessbibliothek }
     *     
     */
    public Prozessbibliothek getProzessbibliothek() {
        return prozessbibliothek;
    }

    /**
     * Sets the value of the prozessbibliothek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prozessbibliothek }
     *     
     */
    public void setProzessbibliothek(Prozessbibliothek value) {
        this.prozessbibliothek = value;
    }

}
