//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Angaben im Prozesssteckbrief zum Auslöser oder zum Ergebnis eines Prozesses. Es kann die ID eines Formulars, die ID eines Prozesses oder eine textuelle Beschreibung angegeben werden. Eine der Angaben sollte mindestens erfolgen.
 * 
 * <p>Java class for AusloeserErgebnis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AusloeserErgebnis"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="formularID" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *         &lt;element name="prozessID" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *         &lt;element name="textuelleBeschreibung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AusloeserErgebnis", propOrder = {
    "formularID",
    "prozessID",
    "textuelleBeschreibung"
})
public class AusloeserErgebnis {

    protected String formularID;
    protected String prozessID;
    protected String textuelleBeschreibung;

    /**
     * Gets the value of the formularID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormularID() {
        return formularID;
    }

    /**
     * Sets the value of the formularID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormularID(String value) {
        this.formularID = value;
    }

    /**
     * Gets the value of the prozessID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProzessID() {
        return prozessID;
    }

    /**
     * Sets the value of the prozessID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProzessID(String value) {
        this.prozessID = value;
    }

    /**
     * Gets the value of the textuelleBeschreibung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextuelleBeschreibung() {
        return textuelleBeschreibung;
    }

    /**
     * Sets the value of the textuelleBeschreibung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextuelleBeschreibung(String value) {
        this.textuelleBeschreibung = value;
    }

}
