//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieser Datentyp bildet die Basis für die in XProzess definierten Nachrichten. Er enthält Informationen, die für jede Nachricht relevant sind.
 * 
 * <p>Java class for Basisnachricht complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Basisnachricht"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nachrichtenkopf" type="{http://www.regierung-mv.de/xprozess/2}Nachrichtenkopf"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="produkt" use="required" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" /&gt;
 *       &lt;attribute name="produkthersteller" use="required" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" /&gt;
 *       &lt;attribute name="produktversion" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" /&gt;
 *       &lt;attribute name="xprozessVersion" use="required" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" fixed="2.0" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Basisnachricht", propOrder = {
    "nachrichtenkopf"
})
@XmlSeeAlso({
    AlleInhalteExport0303 .class,
    AlleInhalteAntwort0302 .class,
    AlleInhalteAnfrage0301 .class,
    ProzessbibliothekExport0203 .class,
    ProzessbibliothekAntwort0202 .class,
    ProzessbibliothekAnfrage0201 .class,
    ProzesskatalogExport0103 .class,
    ProzesskatalogAntwort0102 .class,
    ProzesskatalogAnfrage0101 .class
})
public abstract class Basisnachricht {

    @XmlElement(required = true)
    protected Nachrichtenkopf nachrichtenkopf;
    @XmlAttribute(name = "produkt", required = true)
    protected String produkt;
    @XmlAttribute(name = "produkthersteller", required = true)
    protected String produkthersteller;
    @XmlAttribute(name = "produktversion")
    protected String produktversion;
    @XmlAttribute(name = "xprozessVersion", required = true)
    protected String xprozessVersion;

    /**
     * Gets the value of the nachrichtenkopf property.
     * 
     * @return
     *     possible object is
     *     {@link Nachrichtenkopf }
     *     
     */
    public Nachrichtenkopf getNachrichtenkopf() {
        return nachrichtenkopf;
    }

    /**
     * Sets the value of the nachrichtenkopf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nachrichtenkopf }
     *     
     */
    public void setNachrichtenkopf(Nachrichtenkopf value) {
        this.nachrichtenkopf = value;
    }

    /**
     * Gets the value of the produkt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdukt() {
        return produkt;
    }

    /**
     * Sets the value of the produkt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdukt(String value) {
        this.produkt = value;
    }

    /**
     * Gets the value of the produkthersteller property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdukthersteller() {
        return produkthersteller;
    }

    /**
     * Sets the value of the produkthersteller property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdukthersteller(String value) {
        this.produkthersteller = value;
    }

    /**
     * Gets the value of the produktversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduktversion() {
        return produktversion;
    }

    /**
     * Sets the value of the produktversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduktversion(String value) {
        this.produktversion = value;
    }

    /**
     * Gets the value of the xprozessVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXprozessVersion() {
        if (xprozessVersion == null) {
            return "2.0";
        } else {
            return xprozessVersion;
        }
    }

    /**
     * Sets the value of the xprozessVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXprozessVersion(String value) {
        this.xprozessVersion = value;
    }

}
