//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Metadaten zu einer Datei des Prozessmodells.
 * 
 * <p>Java class for Datei complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Datei"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dateiname" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *         &lt;element name="modellierungsmethode" type="{http://www.regierung-mv.de/xprozess/2}Modellierungsmethode"/&gt;
 *         &lt;element name="mimeType" type="{http://www.regierung-mv.de/xprozess/2}Code.MimeType"/&gt;
 *         &lt;element name="inhalt" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Datei", propOrder = {
    "dateiname",
    "modellierungsmethode",
    "mimeType",
    "inhalt"
})
public class Datei {

    @XmlElement(required = true)
    protected String dateiname;
    @XmlElement(required = true)
    protected Modellierungsmethode modellierungsmethode;
    @XmlElement(required = true)
    protected CodeMimeType mimeType;
    @XmlElement(required = true)
    protected byte[] inhalt;

    /**
     * Gets the value of the dateiname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateiname() {
        return dateiname;
    }

    /**
     * Sets the value of the dateiname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateiname(String value) {
        this.dateiname = value;
    }

    /**
     * Gets the value of the modellierungsmethode property.
     * 
     * @return
     *     possible object is
     *     {@link Modellierungsmethode }
     *     
     */
    public Modellierungsmethode getModellierungsmethode() {
        return modellierungsmethode;
    }

    /**
     * Sets the value of the modellierungsmethode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modellierungsmethode }
     *     
     */
    public void setModellierungsmethode(Modellierungsmethode value) {
        this.modellierungsmethode = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeMimeType }
     *     
     */
    public CodeMimeType getMimeType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeMimeType }
     *     
     */
    public void setMimeType(CodeMimeType value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the inhalt property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getInhalt() {
        return inhalt;
    }

    /**
     * Sets the value of the inhalt property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setInhalt(byte[] value) {
        this.inhalt = value;
    }

}
