//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Die Daten, die in eine Aktivitätengruppe eingehen (eingehende Daten, empfangene Daten) oder aus einer Aktivitätengruppe ausgehen (ausgehende Daten, bereitgestellte Daten). Die Daten können durch durch einen Verweis auf den FIM-Baustein Formulare angegeben werden.
 * 
 * <p>Java class for Daten complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Daten"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="formularverweis" type="{http://www.regierung-mv.de/xprozess/2}Formularverweis"/&gt;
 *         &lt;element name="textuelleBeschreibung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Daten", propOrder = {
    "formularverweis",
    "textuelleBeschreibung"
})
public class Daten {

    protected Formularverweis formularverweis;
    protected String textuelleBeschreibung;

    /**
     * Gets the value of the formularverweis property.
     * 
     * @return
     *     possible object is
     *     {@link Formularverweis }
     *     
     */
    public Formularverweis getFormularverweis() {
        return formularverweis;
    }

    /**
     * Sets the value of the formularverweis property.
     * 
     * @param value
     *     allowed object is
     *     {@link Formularverweis }
     *     
     */
    public void setFormularverweis(Formularverweis value) {
        this.formularverweis = value;
    }

    /**
     * Gets the value of the textuelleBeschreibung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextuelleBeschreibung() {
        return textuelleBeschreibung;
    }

    /**
     * Sets the value of the textuelleBeschreibung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextuelleBeschreibung(String value) {
        this.textuelleBeschreibung = value;
    }

}
