//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Spezifikation von Daten durch Verweis auf den FIM-Baustein Formulare. Es stehen dabei unterschiedliche Detaillierungsstufen zur Verfügung. Von der gröbsten zur feinsten Detaillierung sind dies die Folgenden:
 * 
 * 
 * Wenn nur eine Formularsteckbrief-ID angegeben wird, dann wird auf den Typ des Formulars verwiesen (z.B. Gewerbeanmeldung), ohne auf die Version und die konkrete Ausgestaltung des Formulars einzugehen.
 * Wenn zusätzlich die Stammformular-ID und die Stammformular-Version angegeben werden, wird auf ein konkretes Stammformular als Ganzes mit definiertem Inhalt (Felder und Feldgruppen) referenziert.
 * Über die Nutzung zusätzlicher Element-IDs kann in dem referenzierten Stammformular auf einzelne Datenbereiche (Feldgruppen) oder Datenfelder verwiesen werden.
 * 
 * <p>Java class for Formularverweis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Formularverweis"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="formularsteckbriefID" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *         &lt;element name="stammformularID" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *         &lt;element name="stammformularVersion" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *         &lt;element name="elementId" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Formularverweis", propOrder = {
    "formularsteckbriefID",
    "stammformularID",
    "stammformularVersion",
    "elementId"
})
public class Formularverweis {

    @XmlElement(required = true)
    protected String formularsteckbriefID;
    protected String stammformularID;
    protected String stammformularVersion;
    protected List<String> elementId;

    /**
     * Gets the value of the formularsteckbriefID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormularsteckbriefID() {
        return formularsteckbriefID;
    }

    /**
     * Sets the value of the formularsteckbriefID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormularsteckbriefID(String value) {
        this.formularsteckbriefID = value;
    }

    /**
     * Gets the value of the stammformularID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStammformularID() {
        return stammformularID;
    }

    /**
     * Sets the value of the stammformularID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStammformularID(String value) {
        this.stammformularID = value;
    }

    /**
     * Gets the value of the stammformularVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStammformularVersion() {
        return stammformularVersion;
    }

    /**
     * Sets the value of the stammformularVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStammformularVersion(String value) {
        this.stammformularVersion = value;
    }

    /**
     * Gets the value of the elementId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elementId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElementId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getElementId() {
        if (elementId == null) {
            elementId = new ArrayList<String>();
        }
        return this.elementId;
    }

}
