//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uni.jena.fim.xprocess.v2.core package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uni.jena.fim.xprocess.v2.core
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Strukturbeschreibung }
     * 
     */
    public Strukturbeschreibung createStrukturbeschreibung() {
        return new Strukturbeschreibung();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute }
     * 
     */
    public SpezifischeAttribute createSpezifischeAttribute() {
        return new SpezifischeAttribute();
    }

    /**
     * Create an instance of {@link Prozessklasse }
     * 
     */
    public Prozessklasse createProzessklasse() {
        return new Prozessklasse();
    }

    /**
     * Create an instance of {@link ProzesskatalogAnfrage0101 }
     * 
     */
    public ProzesskatalogAnfrage0101 createProzesskatalogAnfrage0101() {
        return new ProzesskatalogAnfrage0101();
    }

    /**
     * Create an instance of {@link Nachrichtenkopf }
     * 
     */
    public Nachrichtenkopf createNachrichtenkopf() {
        return new Nachrichtenkopf();
    }

    /**
     * Create an instance of {@link SuchprofilProzessklasse }
     * 
     */
    public SuchprofilProzessklasse createSuchprofilProzessklasse() {
        return new SuchprofilProzessklasse();
    }

    /**
     * Create an instance of {@link ProzesskatalogAntwort0102 }
     * 
     */
    public ProzesskatalogAntwort0102 createProzesskatalogAntwort0102() {
        return new ProzesskatalogAntwort0102();
    }

    /**
     * Create an instance of {@link Prozesskatalog }
     * 
     */
    public Prozesskatalog createProzesskatalog() {
        return new Prozesskatalog();
    }

    /**
     * Create an instance of {@link ProzesskatalogExport0103 }
     * 
     */
    public ProzesskatalogExport0103 createProzesskatalogExport0103() {
        return new ProzesskatalogExport0103();
    }

    /**
     * Create an instance of {@link ProzessbibliothekAnfrage0201 }
     * 
     */
    public ProzessbibliothekAnfrage0201 createProzessbibliothekAnfrage0201() {
        return new ProzessbibliothekAnfrage0201();
    }

    /**
     * Create an instance of {@link SuchprofilProzess }
     * 
     */
    public SuchprofilProzess createSuchprofilProzess() {
        return new SuchprofilProzess();
    }

    /**
     * Create an instance of {@link ProzessbibliothekAntwort0202 }
     * 
     */
    public ProzessbibliothekAntwort0202 createProzessbibliothekAntwort0202() {
        return new ProzessbibliothekAntwort0202();
    }

    /**
     * Create an instance of {@link Prozessbibliothek }
     * 
     */
    public Prozessbibliothek createProzessbibliothek() {
        return new Prozessbibliothek();
    }

    /**
     * Create an instance of {@link ProzessbibliothekExport0203 }
     * 
     */
    public ProzessbibliothekExport0203 createProzessbibliothekExport0203() {
        return new ProzessbibliothekExport0203();
    }

    /**
     * Create an instance of {@link AlleInhalteAnfrage0301 }
     * 
     */
    public AlleInhalteAnfrage0301 createAlleInhalteAnfrage0301() {
        return new AlleInhalteAnfrage0301();
    }

    /**
     * Create an instance of {@link SuchprofilAlleInhalte }
     * 
     */
    public SuchprofilAlleInhalte createSuchprofilAlleInhalte() {
        return new SuchprofilAlleInhalte();
    }

    /**
     * Create an instance of {@link AlleInhalteAntwort0302 }
     * 
     */
    public AlleInhalteAntwort0302 createAlleInhalteAntwort0302() {
        return new AlleInhalteAntwort0302();
    }

    /**
     * Create an instance of {@link AlleInhalteExport0303 }
     * 
     */
    public AlleInhalteExport0303 createAlleInhalteExport0303() {
        return new AlleInhalteExport0303();
    }

    /**
     * Create an instance of {@link Aktivitaetengruppe }
     * 
     */
    public Aktivitaetengruppe createAktivitaetengruppe() {
        return new Aktivitaetengruppe();
    }

    /**
     * Create an instance of {@link AusloeserErgebnis }
     * 
     */
    public AusloeserErgebnis createAusloeserErgebnis() {
        return new AusloeserErgebnis();
    }

    /**
     * Create an instance of {@link CodeBearbeitungsart }
     * 
     */
    public CodeBearbeitungsart createCodeBearbeitungsart() {
        return new CodeBearbeitungsart();
    }

    /**
     * Create an instance of {@link CodeBeteiligungsform }
     * 
     */
    public CodeBeteiligungsform createCodeBeteiligungsform() {
        return new CodeBeteiligungsform();
    }

    /**
     * Create an instance of {@link CodeBezirk }
     * 
     */
    public CodeBezirk createCodeBezirk() {
        return new CodeBezirk();
    }

    /**
     * Create an instance of {@link CodeBundesland }
     * 
     */
    public CodeBundesland createCodeBundesland() {
        return new CodeBundesland();
    }

    /**
     * Create an instance of {@link CodeDatentyp }
     * 
     */
    public CodeDatentyp createCodeDatentyp() {
        return new CodeDatentyp();
    }

    /**
     * Create an instance of {@link CodeDetaillierungsstufe }
     * 
     */
    public CodeDetaillierungsstufe createCodeDetaillierungsstufe() {
        return new CodeDetaillierungsstufe();
    }

    /**
     * Create an instance of {@link CodeEntscheidungsart }
     * 
     */
    public CodeEntscheidungsart createCodeEntscheidungsart() {
        return new CodeEntscheidungsart();
    }

    /**
     * Create an instance of {@link CodeFormellePruefung }
     * 
     */
    public CodeFormellePruefung createCodeFormellePruefung() {
        return new CodeFormellePruefung();
    }

    /**
     * Create an instance of {@link CodeGemeindeschluessel }
     * 
     */
    public CodeGemeindeschluessel createCodeGemeindeschluessel() {
        return new CodeGemeindeschluessel();
    }

    /**
     * Create an instance of {@link CodeGemeindeverband }
     * 
     */
    public CodeGemeindeverband createCodeGemeindeverband() {
        return new CodeGemeindeverband();
    }

    /**
     * Create an instance of {@link CodeHandlungsform }
     * 
     */
    public CodeHandlungsform createCodeHandlungsform() {
        return new CodeHandlungsform();
    }

    /**
     * Create an instance of {@link CodeHandlungsgrundlagenart }
     * 
     */
    public CodeHandlungsgrundlagenart createCodeHandlungsgrundlagenart() {
        return new CodeHandlungsgrundlagenart();
    }

    /**
     * Create an instance of {@link CodeKreis }
     * 
     */
    public CodeKreis createCodeKreis() {
        return new CodeKreis();
    }

    /**
     * Create an instance of {@link CodeMimeType }
     * 
     */
    public CodeMimeType createCodeMimeType() {
        return new CodeMimeType();
    }

    /**
     * Create an instance of {@link CodeModellierungsmethode }
     * 
     */
    public CodeModellierungsmethode createCodeModellierungsmethode() {
        return new CodeModellierungsmethode();
    }

    /**
     * Create an instance of {@link CodeNachricht }
     * 
     */
    public CodeNachricht createCodeNachricht() {
        return new CodeNachricht();
    }

    /**
     * Create an instance of {@link CodeOperativesZiel }
     * 
     */
    public CodeOperativesZiel createCodeOperativesZiel() {
        return new CodeOperativesZiel();
    }

    /**
     * Create an instance of {@link CodeProzessrolle }
     * 
     */
    public CodeProzessrolle createCodeProzessrolle() {
        return new CodeProzessrolle();
    }

    /**
     * Create an instance of {@link CodeReferenzaktivitaetengruppe }
     * 
     */
    public CodeReferenzaktivitaetengruppe createCodeReferenzaktivitaetengruppe() {
        return new CodeReferenzaktivitaetengruppe();
    }

    /**
     * Create an instance of {@link CodeRegionalschluessel }
     * 
     */
    public CodeRegionalschluessel createCodeRegionalschluessel() {
        return new CodeRegionalschluessel();
    }

    /**
     * Create an instance of {@link CodeStaat }
     * 
     */
    public CodeStaat createCodeStaat() {
        return new CodeStaat();
    }

    /**
     * Create an instance of {@link CodeStatus }
     * 
     */
    public CodeStatus createCodeStatus() {
        return new CodeStatus();
    }

    /**
     * Create an instance of {@link CodeUebermittlungsart }
     * 
     */
    public CodeUebermittlungsart createCodeUebermittlungsart() {
        return new CodeUebermittlungsart();
    }

    /**
     * Create an instance of {@link CodeVerfahrensart }
     * 
     */
    public CodeVerfahrensart createCodeVerfahrensart() {
        return new CodeVerfahrensart();
    }

    /**
     * Create an instance of {@link CodeVersionen }
     * 
     */
    public CodeVersionen createCodeVersionen() {
        return new CodeVersionen();
    }

    /**
     * Create an instance of {@link CodeZwecksetzung }
     * 
     */
    public CodeZwecksetzung createCodeZwecksetzung() {
        return new CodeZwecksetzung();
    }

    /**
     * Create an instance of {@link Datei }
     * 
     */
    public Datei createDatei() {
        return new Datei();
    }

    /**
     * Create an instance of {@link Daten }
     * 
     */
    public Daten createDaten() {
        return new Daten();
    }

    /**
     * Create an instance of {@link DatenBereitgestellt }
     * 
     */
    public DatenBereitgestellt createDatenBereitgestellt() {
        return new DatenBereitgestellt();
    }

    /**
     * Create an instance of {@link DatenEmpfangen }
     * 
     */
    public DatenEmpfangen createDatenEmpfangen() {
        return new DatenEmpfangen();
    }

    /**
     * Create an instance of {@link Formularverweis }
     * 
     */
    public Formularverweis createFormularverweis() {
        return new Formularverweis();
    }

    /**
     * Create an instance of {@link Handlungsgrundlage }
     * 
     */
    public Handlungsgrundlage createHandlungsgrundlage() {
        return new Handlungsgrundlage();
    }

    /**
     * Create an instance of {@link Herausgeber }
     * 
     */
    public Herausgeber createHerausgeber() {
        return new Herausgeber();
    }

    /**
     * Create an instance of {@link Klassifikation }
     * 
     */
    public Klassifikation createKlassifikation() {
        return new Klassifikation();
    }

    /**
     * Create an instance of {@link Merkmal }
     * 
     */
    public Merkmal createMerkmal() {
        return new Merkmal();
    }

    /**
     * Create an instance of {@link Modellierungsmethode }
     * 
     */
    public Modellierungsmethode createModellierungsmethode() {
        return new Modellierungsmethode();
    }

    /**
     * Create an instance of {@link Prozess }
     * 
     */
    public Prozess createProzess() {
        return new Prozess();
    }

    /**
     * Create an instance of {@link Prozessmodell }
     * 
     */
    public Prozessmodell createProzessmodell() {
        return new Prozessmodell();
    }

    /**
     * Create an instance of {@link Prozesssteckbrief }
     * 
     */
    public Prozesssteckbrief createProzesssteckbrief() {
        return new Prozesssteckbrief();
    }

    /**
     * Create an instance of {@link Prozessteilnehmer }
     * 
     */
    public Prozessteilnehmer createProzessteilnehmer() {
        return new Prozessteilnehmer();
    }

    /**
     * Create an instance of {@link ReferenzProzessklasse }
     * 
     */
    public ReferenzProzessklasse createReferenzProzessklasse() {
        return new ReferenzProzessklasse();
    }

    /**
     * Create an instance of {@link SuchprofilKlassifikation }
     * 
     */
    public SuchprofilKlassifikation createSuchprofilKlassifikation() {
        return new SuchprofilKlassifikation();
    }

    /**
     * Create an instance of {@link SuchprofilMerkmal }
     * 
     */
    public SuchprofilMerkmal createSuchprofilMerkmal() {
        return new SuchprofilMerkmal();
    }

    /**
     * Create an instance of {@link SuchprofilSpezifischerProzess }
     * 
     */
    public SuchprofilSpezifischerProzess createSuchprofilSpezifischerProzess() {
        return new SuchprofilSpezifischerProzess();
    }

    /**
     * Create an instance of {@link VerwaltungspolitischeKodierung }
     * 
     */
    public VerwaltungspolitischeKodierung createVerwaltungspolitischeKodierung() {
        return new VerwaltungspolitischeKodierung();
    }

    /**
     * Create an instance of {@link Zeitraum }
     * 
     */
    public Zeitraum createZeitraum() {
        return new Zeitraum();
    }

    /**
     * Create an instance of {@link Zustandsangaben }
     * 
     */
    public Zustandsangaben createZustandsangaben() {
        return new Zustandsangaben();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

    /**
     * Create an instance of {@link Strukturbeschreibung.StrukturbeschreibungFIM }
     * 
     */
    public Strukturbeschreibung.StrukturbeschreibungFIM createStrukturbeschreibungStrukturbeschreibungFIM() {
        return new Strukturbeschreibung.StrukturbeschreibungFIM();
    }

    /**
     * Create an instance of {@link Strukturbeschreibung.StrukturbeschreibungSonstige }
     * 
     */
    public Strukturbeschreibung.StrukturbeschreibungSonstige createStrukturbeschreibungStrukturbeschreibungSonstige() {
        return new Strukturbeschreibung.StrukturbeschreibungSonstige();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute.SpezifischeAttribute1 }
     * 
     */
    public SpezifischeAttribute.SpezifischeAttribute1 createSpezifischeAttributeSpezifischeAttribute1() {
        return new SpezifischeAttribute.SpezifischeAttribute1();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute.SpezifischeAttribute2 }
     * 
     */
    public SpezifischeAttribute.SpezifischeAttribute2 createSpezifischeAttributeSpezifischeAttribute2() {
        return new SpezifischeAttribute.SpezifischeAttribute2();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute.SpezifischeAttribute3 }
     * 
     */
    public SpezifischeAttribute.SpezifischeAttribute3 createSpezifischeAttributeSpezifischeAttribute3() {
        return new SpezifischeAttribute.SpezifischeAttribute3();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute.SpezifischeAttribute4 }
     * 
     */
    public SpezifischeAttribute.SpezifischeAttribute4 createSpezifischeAttributeSpezifischeAttribute4() {
        return new SpezifischeAttribute.SpezifischeAttribute4();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute.SpezifischeAttribute5 }
     * 
     */
    public SpezifischeAttribute.SpezifischeAttribute5 createSpezifischeAttributeSpezifischeAttribute5() {
        return new SpezifischeAttribute.SpezifischeAttribute5();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute.SpezifischeAttribute6 }
     * 
     */
    public SpezifischeAttribute.SpezifischeAttribute6 createSpezifischeAttributeSpezifischeAttribute6() {
        return new SpezifischeAttribute.SpezifischeAttribute6();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute.SpezifischeAttribute7 }
     * 
     */
    public SpezifischeAttribute.SpezifischeAttribute7 createSpezifischeAttributeSpezifischeAttribute7() {
        return new SpezifischeAttribute.SpezifischeAttribute7();
    }

    /**
     * Create an instance of {@link SpezifischeAttribute.SpezifischeAttribute8 }
     * 
     */
    public SpezifischeAttribute.SpezifischeAttribute8 createSpezifischeAttributeSpezifischeAttribute8() {
        return new SpezifischeAttribute.SpezifischeAttribute8();
    }

    /**
     * Create an instance of {@link Prozessklasse.Gliederungsebene }
     * 
     */
    public Prozessklasse.Gliederungsebene createProzessklasseGliederungsebene() {
        return new Prozessklasse.Gliederungsebene();
    }

}
