//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Das Prozessmodell wird in Form von verschiedenen Dateien (Prozessmodelldatei, Visualisierungsdatei, Beschreibungsdatei) spezifiziert.
 * 
 * <p>Java class for Prozessmodell complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Prozessmodell"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="prozessmodelldatei" type="{http://www.regierung-mv.de/xprozess/2}Datei" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="visualisierungsdatei" type="{http://www.regierung-mv.de/xprozess/2}Datei" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="beschreibungsdatei" type="{http://www.regierung-mv.de/xprozess/2}Datei" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Prozessmodell", propOrder = {
    "prozessmodelldatei",
    "visualisierungsdatei",
    "beschreibungsdatei"
})
public class Prozessmodell {

    protected List<Datei> prozessmodelldatei;
    protected List<Datei> visualisierungsdatei;
    protected List<Datei> beschreibungsdatei;

    /**
     * Gets the value of the prozessmodelldatei property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the prozessmodelldatei property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProzessmodelldatei().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datei }
     * 
     * 
     */
    public List<Datei> getProzessmodelldatei() {
        if (prozessmodelldatei == null) {
            prozessmodelldatei = new ArrayList<Datei>();
        }
        return this.prozessmodelldatei;
    }

    /**
     * Gets the value of the visualisierungsdatei property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visualisierungsdatei property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisualisierungsdatei().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datei }
     * 
     * 
     */
    public List<Datei> getVisualisierungsdatei() {
        if (visualisierungsdatei == null) {
            visualisierungsdatei = new ArrayList<Datei>();
        }
        return this.visualisierungsdatei;
    }

    /**
     * Gets the value of the beschreibungsdatei property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the beschreibungsdatei property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBeschreibungsdatei().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Datei }
     * 
     * 
     */
    public List<Datei> getBeschreibungsdatei() {
        if (beschreibungsdatei == null) {
            beschreibungsdatei = new ArrayList<Datei>();
        }
        return this.beschreibungsdatei;
    }

}
