//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dieses Element kann genutzt werden, um zusätzliche Informationen zu den Modellierungselementen des Prozessmodells entsprechend der Modellierungsmethode hinzuzufügen.
 * 
 * <p>Java class for Strukturbeschreibung complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Strukturbeschreibung"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="modellierungsmethode" type="{http://www.regierung-mv.de/xprozess/2}Modellierungsmethode"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="strukturbeschreibungFIM"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="aktivitaetengruppe" type="{http://www.regierung-mv.de/xprozess/2}Aktivitaetengruppe" maxOccurs="unbounded"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="strukturbeschreibungSonstige"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;any/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Strukturbeschreibung", propOrder = {
    "modellierungsmethode",
    "strukturbeschreibungFIM",
    "strukturbeschreibungSonstige"
})
public class Strukturbeschreibung {

    @XmlElement(required = true)
    protected Modellierungsmethode modellierungsmethode;
    protected Strukturbeschreibung.StrukturbeschreibungFIM strukturbeschreibungFIM;
    protected Strukturbeschreibung.StrukturbeschreibungSonstige strukturbeschreibungSonstige;

    /**
     * Gets the value of the modellierungsmethode property.
     * 
     * @return
     *     possible object is
     *     {@link Modellierungsmethode }
     *     
     */
    public Modellierungsmethode getModellierungsmethode() {
        return modellierungsmethode;
    }

    /**
     * Sets the value of the modellierungsmethode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Modellierungsmethode }
     *     
     */
    public void setModellierungsmethode(Modellierungsmethode value) {
        this.modellierungsmethode = value;
    }

    /**
     * Gets the value of the strukturbeschreibungFIM property.
     * 
     * @return
     *     possible object is
     *     {@link Strukturbeschreibung.StrukturbeschreibungFIM }
     *     
     */
    public Strukturbeschreibung.StrukturbeschreibungFIM getStrukturbeschreibungFIM() {
        return strukturbeschreibungFIM;
    }

    /**
     * Sets the value of the strukturbeschreibungFIM property.
     * 
     * @param value
     *     allowed object is
     *     {@link Strukturbeschreibung.StrukturbeschreibungFIM }
     *     
     */
    public void setStrukturbeschreibungFIM(Strukturbeschreibung.StrukturbeschreibungFIM value) {
        this.strukturbeschreibungFIM = value;
    }

    /**
     * Gets the value of the strukturbeschreibungSonstige property.
     * 
     * @return
     *     possible object is
     *     {@link Strukturbeschreibung.StrukturbeschreibungSonstige }
     *     
     */
    public Strukturbeschreibung.StrukturbeschreibungSonstige getStrukturbeschreibungSonstige() {
        return strukturbeschreibungSonstige;
    }

    /**
     * Sets the value of the strukturbeschreibungSonstige property.
     * 
     * @param value
     *     allowed object is
     *     {@link Strukturbeschreibung.StrukturbeschreibungSonstige }
     *     
     */
    public void setStrukturbeschreibungSonstige(Strukturbeschreibung.StrukturbeschreibungSonstige value) {
        this.strukturbeschreibungSonstige = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="aktivitaetengruppe" type="{http://www.regierung-mv.de/xprozess/2}Aktivitaetengruppe" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aktivitaetengruppe"
    })
    public static class StrukturbeschreibungFIM {

        @XmlElement(required = true)
        protected List<Aktivitaetengruppe> aktivitaetengruppe;

        /**
         * Gets the value of the aktivitaetengruppe property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the aktivitaetengruppe property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAktivitaetengruppe().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Aktivitaetengruppe }
         * 
         * 
         */
        public List<Aktivitaetengruppe> getAktivitaetengruppe() {
            if (aktivitaetengruppe == null) {
                aktivitaetengruppe = new ArrayList<Aktivitaetengruppe>();
            }
            return this.aktivitaetengruppe;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;any/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class StrukturbeschreibungSonstige {

        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }

}
