//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Es werden nur Objekte übertragen, die Klassifikationsangaben haben, die den in sucheKlassifikation angegebenen entsprechen.
 * 
 * <p>Java class for Suchprofil.Klassifikation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Suchprofil.Klassifikation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ordnungsrahmenName" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *         &lt;element name="ordnungsrahmenVersion" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *         &lt;element name="klasseID" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Suchprofil.Klassifikation", propOrder = {
    "ordnungsrahmenName",
    "ordnungsrahmenVersion",
    "klasseID"
})
public class SuchprofilKlassifikation {

    @XmlElement(required = true)
    protected String ordnungsrahmenName;
    protected String ordnungsrahmenVersion;
    protected String klasseID;

    /**
     * Gets the value of the ordnungsrahmenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdnungsrahmenName() {
        return ordnungsrahmenName;
    }

    /**
     * Sets the value of the ordnungsrahmenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdnungsrahmenName(String value) {
        this.ordnungsrahmenName = value;
    }

    /**
     * Gets the value of the ordnungsrahmenVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrdnungsrahmenVersion() {
        return ordnungsrahmenVersion;
    }

    /**
     * Sets the value of the ordnungsrahmenVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrdnungsrahmenVersion(String value) {
        this.ordnungsrahmenVersion = value;
    }

    /**
     * Gets the value of the klasseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKlasseID() {
        return klasseID;
    }

    /**
     * Sets the value of the klasseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKlasseID(String value) {
        this.klasseID = value;
    }

}
