//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.06 at 10:07:40 AM UTC 
//


package uni.jena.fim.xprocess.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Angaben im Suchprofil zu einem spezifischen Prozess.
 * 
 * <p>Java class for Suchprofil.SpezifischerProzess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Suchprofil.SpezifischerProzess"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="prozessID" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *         &lt;element name="spezifischeVersion" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Suchprofil.SpezifischerProzess", propOrder = {
    "prozessID",
    "spezifischeVersion"
})
public class SuchprofilSpezifischerProzess {

    @XmlElement(required = true)
    protected String prozessID;
    protected String spezifischeVersion;

    /**
     * Gets the value of the prozessID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProzessID() {
        return prozessID;
    }

    /**
     * Sets the value of the prozessID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProzessID(String value) {
        this.prozessID = value;
    }

    /**
     * Gets the value of the spezifischeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpezifischeVersion() {
        return spezifischeVersion;
    }

    /**
     * Sets the value of the spezifischeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpezifischeVersion(String value) {
        this.spezifischeVersion = value;
    }

}
