//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 12:04:25 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/codelist/ns/genericode/1.0/")
package uni.jena.fim.codelist.core;
