//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Referenz auf eine Codeliste.
 * 
 * <p>Java class for CodelisteReferenz complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CodelisteReferenz"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifikation" type="{urn:xoev-de:fim:standard:xdatenfelder_2}ElementIdentifikation"/&gt;
 *         &lt;element name="genericodeIdentification" type="{urn:xoev-de:fim:standard:xdatenfelder_2}GenericodeIdentification"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CodelisteReferenz", propOrder = {
    "identifikation",
    "genericodeIdentification"
})
public class CodelisteReferenz {

    @XmlElement(required = true)
    protected ElementIdentifikation identifikation;
    @XmlElement(required = true)
    protected GenericodeIdentification genericodeIdentification;

    /**
     * Gets the value of the identifikation property.
     * 
     * @return
     *     possible object is
     *     {@link ElementIdentifikation }
     *     
     */
    public ElementIdentifikation getIdentifikation() {
        return identifikation;
    }

    /**
     * Sets the value of the identifikation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementIdentifikation }
     *     
     */
    public void setIdentifikation(ElementIdentifikation value) {
        this.identifikation = value;
    }

    /**
     * Gets the value of the genericodeIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link GenericodeIdentification }
     *     
     */
    public GenericodeIdentification getGenericodeIdentification() {
        return genericodeIdentification;
    }

    /**
     * Sets the value of the genericodeIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericodeIdentification }
     *     
     */
    public void setGenericodeIdentification(GenericodeIdentification value) {
        this.genericodeIdentification = value;
    }

}
