//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Eine Codeliste ist eine Liste von vordefinierten Werten.
 * 
 * <p>Java class for Codeliste complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Codeliste"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:xoev-de:fim:standard:xdatenfelder_2}AllgemeineAngaben"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="genericodeIdentification" type="{urn:xoev-de:fim:standard:xdatenfelder_2}GenericodeIdentification"/&gt;
 *         &lt;element name="langname" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *         &lt;element name="genericode" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Genericode"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Codeliste", propOrder = {
    "genericodeIdentification",
    "langname",
    "genericode"
})
public class Codeliste
    extends AllgemeineAngaben
{

    @XmlElement(required = true)
    protected GenericodeIdentification genericodeIdentification;
    @XmlElement(required = true)
    protected String langname;
    @XmlElement(required = true)
    protected Genericode genericode;

    /**
     * Gets the value of the genericodeIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link GenericodeIdentification }
     *     
     */
    public GenericodeIdentification getGenericodeIdentification() {
        return genericodeIdentification;
    }

    /**
     * Sets the value of the genericodeIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericodeIdentification }
     *     
     */
    public void setGenericodeIdentification(GenericodeIdentification value) {
        this.genericodeIdentification = value;
    }

    /**
     * Gets the value of the langname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangname() {
        return langname;
    }

    /**
     * Sets the value of the langname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangname(String value) {
        this.langname = value;
    }

    /**
     * Gets the value of the genericode property.
     * 
     * @return
     *     possible object is
     *     {@link Genericode }
     *     
     */
    public Genericode getGenericode() {
        return genericode;
    }

    /**
     * Sets the value of the genericode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Genericode }
     *     
     */
    public void setGenericode(Genericode value) {
        this.genericode = value;
    }

}
