//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Eine Datenfeldgruppe besteht aus einer Sammlung von Datenfeldern und/oder Datenfeldgruppen.
 * 
 * <p>Java class for Datenfeldgruppe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Datenfeldgruppe"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:xoev-de:fim:standard:xdatenfelder_2}Schemaelementangaben"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="regel" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Regel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="struktur" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Struktur" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Datenfeldgruppe", propOrder = {
    "regel",
    "struktur"
})
public class Datenfeldgruppe
    extends Schemaelementangaben
{

    protected List<Regel> regel;
    protected List<Struktur> struktur;

    /**
     * Gets the value of the regel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Regel }
     * 
     * 
     */
    public List<Regel> getRegel() {
        if (regel == null) {
            regel = new ArrayList<Regel>();
        }
        return this.regel;
    }

    /**
     * Gets the value of the struktur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the struktur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStruktur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Struktur }
     * 
     * 
     */
    public List<Struktur> getStruktur() {
        if (struktur == null) {
            struktur = new ArrayList<Struktur>();
        }
        return this.struktur;
    }

}
