//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Die Feldart gibt die grundsätzliche Art des Feldes an.
 * 
 * <p>Java class for Datenfeld complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Datenfeld"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:xoev-de:fim:standard:xdatenfelder_2}Schemaelementangaben"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="feldart" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.Feldart"/&gt;
 *         &lt;element name="datentyp" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.Datentyp"/&gt;
 *         &lt;element name="praezisierung" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *         &lt;element name="inhalt" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *         &lt;element name="codelisteReferenz" type="{urn:xoev-de:fim:standard:xdatenfelder_2}CodelisteReferenz" minOccurs="0"/&gt;
 *         &lt;element name="regel" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Regel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Datenfeld", propOrder = {
    "feldart",
    "datentyp",
    "praezisierung",
    "inhalt",
    "codelisteReferenz",
    "regel"
})
public class Datenfeld
    extends Schemaelementangaben
{

    @XmlElement(required = true)
    protected CodeFeldart feldart;
    @XmlElement(required = true)
    protected CodeDatentyp datentyp;
    @XmlElement(required = true)
    protected String praezisierung;
    @XmlElement(required = true)
    protected String inhalt;
    protected CodelisteReferenz codelisteReferenz;
    protected List<Regel> regel;

    /**
     * Gets the value of the feldart property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFeldart }
     *     
     */
    public CodeFeldart getFeldart() {
        return feldart;
    }

    /**
     * Sets the value of the feldart property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFeldart }
     *     
     */
    public void setFeldart(CodeFeldart value) {
        this.feldart = value;
    }

    /**
     * Gets the value of the datentyp property.
     * 
     * @return
     *     possible object is
     *     {@link CodeDatentyp }
     *     
     */
    public CodeDatentyp getDatentyp() {
        return datentyp;
    }

    /**
     * Sets the value of the datentyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeDatentyp }
     *     
     */
    public void setDatentyp(CodeDatentyp value) {
        this.datentyp = value;
    }

    /**
     * Gets the value of the praezisierung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPraezisierung() {
        return praezisierung;
    }

    /**
     * Sets the value of the praezisierung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPraezisierung(String value) {
        this.praezisierung = value;
    }

    /**
     * Gets the value of the inhalt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInhalt() {
        return inhalt;
    }

    /**
     * Sets the value of the inhalt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInhalt(String value) {
        this.inhalt = value;
    }

    /**
     * Gets the value of the codelisteReferenz property.
     * 
     * @return
     *     possible object is
     *     {@link CodelisteReferenz }
     *     
     */
    public CodelisteReferenz getCodelisteReferenz() {
        return codelisteReferenz;
    }

    /**
     * Sets the value of the codelisteReferenz property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodelisteReferenz }
     *     
     */
    public void setCodelisteReferenz(CodelisteReferenz value) {
        this.codelisteReferenz = value;
    }

    /**
     * Gets the value of the regel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Regel }
     * 
     * 
     */
    public List<Regel> getRegel() {
        if (regel == null) {
            regel = new ArrayList<Regel>();
        }
        return this.regel;
    }

}
