//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Mit einem Dokumentsteckbrief kann im ersten Schritt ein Dokument (Formular) (mit seinen Metadaten) in der Datenfelderbibliothek erfasst werden, ohne gleichzeitig oder direkt anschließend die Struktur des Dokuments (d.h.das zugehörige Stammdatenschema) erstellen zu müssen.
 * 
 * <p>Java class for Dokumentsteckbrief complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Dokumentsteckbrief"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:xoev-de:fim:standard:xdatenfelder_2}AllgemeineAngaben"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isReferenz" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="dokumentart" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="hilfetext" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dokumentsteckbrief", propOrder = {
    "isReferenz",
    "dokumentart",
    "hilfetext"
})
public class Dokumentsteckbrief
    extends AllgemeineAngaben
{

    protected boolean isReferenz;
    @XmlElement(required = true)
    protected String dokumentart;
    protected String hilfetext;

    /**
     * Gets the value of the isReferenz property.
     * 
     */
    public boolean isIsReferenz() {
        return isReferenz;
    }

    /**
     * Sets the value of the isReferenz property.
     * 
     */
    public void setIsReferenz(boolean value) {
        this.isReferenz = value;
    }

    /**
     * Gets the value of the dokumentart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDokumentart() {
        return dokumentart;
    }

    /**
     * Sets the value of the dokumentart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDokumentart(String value) {
        this.dokumentart = value;
    }

    /**
     * Gets the value of the hilfetext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHilfetext() {
        return hilfetext;
    }

    /**
     * Sets the value of the hilfetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHilfetext(String value) {
        this.hilfetext = value;
    }

}
