//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uni.jena.fim.xdatenfelder.core package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uni.jena.fim.xdatenfelder.core
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XdatenfelderDokumentsteckbrief0101 }
     * 
     */
    public XdatenfelderDokumentsteckbrief0101 createXdatenfelderDokumentsteckbrief0101() {
        return new XdatenfelderDokumentsteckbrief0101();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Dokumentsteckbrief }
     * 
     */
    public Dokumentsteckbrief createDokumentsteckbrief() {
        return new Dokumentsteckbrief();
    }

    /**
     * Create an instance of {@link XdatenfelderStammdatenschema0102 }
     * 
     */
    public XdatenfelderStammdatenschema0102 createXdatenfelderStammdatenschema0102() {
        return new XdatenfelderStammdatenschema0102();
    }

    /**
     * Create an instance of {@link Stammdatenschema }
     * 
     */
    public Stammdatenschema createStammdatenschema() {
        return new Stammdatenschema();
    }

    /**
     * Create an instance of {@link XdatenfelderDatenfeldgruppe0103 }
     * 
     */
    public XdatenfelderDatenfeldgruppe0103 createXdatenfelderDatenfeldgruppe0103() {
        return new XdatenfelderDatenfeldgruppe0103();
    }

    /**
     * Create an instance of {@link Datenfeldgruppe }
     * 
     */
    public Datenfeldgruppe createDatenfeldgruppe() {
        return new Datenfeldgruppe();
    }

    /**
     * Create an instance of {@link XdatenfelderDatenfeld0104 }
     * 
     */
    public XdatenfelderDatenfeld0104 createXdatenfelderDatenfeld0104() {
        return new XdatenfelderDatenfeld0104();
    }

    /**
     * Create an instance of {@link Datenfeld }
     * 
     */
    public Datenfeld createDatenfeld() {
        return new Datenfeld();
    }

    /**
     * Create an instance of {@link XdatenfelderCodeliste0105 }
     * 
     */
    public XdatenfelderCodeliste0105 createXdatenfelderCodeliste0105() {
        return new XdatenfelderCodeliste0105();
    }

    /**
     * Create an instance of {@link Codeliste }
     * 
     */
    public Codeliste createCodeliste() {
        return new Codeliste();
    }

    /**
     * Create an instance of {@link CodeAbleitungsmodifikationenRepraesentation }
     * 
     */
    public CodeAbleitungsmodifikationenRepraesentation createCodeAbleitungsmodifikationenRepraesentation() {
        return new CodeAbleitungsmodifikationenRepraesentation();
    }

    /**
     * Create an instance of {@link CodeAbleitungsmodifikationenStruktur }
     * 
     */
    public CodeAbleitungsmodifikationenStruktur createCodeAbleitungsmodifikationenStruktur() {
        return new CodeAbleitungsmodifikationenStruktur();
    }

    /**
     * Create an instance of {@link CodeDatentyp }
     * 
     */
    public CodeDatentyp createCodeDatentyp() {
        return new CodeDatentyp();
    }

    /**
     * Create an instance of {@link CodeElementTyp }
     * 
     */
    public CodeElementTyp createCodeElementTyp() {
        return new CodeElementTyp();
    }

    /**
     * Create an instance of {@link CodeFeldart }
     * 
     */
    public CodeFeldart createCodeFeldart() {
        return new CodeFeldart();
    }

    /**
     * Create an instance of {@link CodeSchemaelementart }
     * 
     */
    public CodeSchemaelementart createCodeSchemaelementart() {
        return new CodeSchemaelementart();
    }

    /**
     * Create an instance of {@link CodeStatus }
     * 
     */
    public CodeStatus createCodeStatus() {
        return new CodeStatus();
    }

    /**
     * Create an instance of {@link CodeSuchfeld }
     * 
     */
    public CodeSuchfeld createCodeSuchfeld() {
        return new CodeSuchfeld();
    }

    /**
     * Create an instance of {@link CodelisteReferenz }
     * 
     */
    public CodelisteReferenz createCodelisteReferenz() {
        return new CodelisteReferenz();
    }

    /**
     * Create an instance of {@link ElementIdentifikation }
     * 
     */
    public ElementIdentifikation createElementIdentifikation() {
        return new ElementIdentifikation();
    }

    /**
     * Create an instance of {@link Enthaelt }
     * 
     */
    public Enthaelt createEnthaelt() {
        return new Enthaelt();
    }

    /**
     * Create an instance of {@link Genericode }
     * 
     */
    public Genericode createGenericode() {
        return new Genericode();
    }

    /**
     * Create an instance of {@link GenericodeIdentification }
     * 
     */
    public GenericodeIdentification createGenericodeIdentification() {
        return new GenericodeIdentification();
    }

    /**
     * Create an instance of {@link Regel }
     * 
     */
    public Regel createRegel() {
        return new Regel();
    }

    /**
     * Create an instance of {@link Struktur }
     * 
     */
    public Struktur createStruktur() {
        return new Struktur();
    }

    /**
     * Create an instance of {@link Suchanfrage }
     * 
     */
    public Suchanfrage createSuchanfrage() {
        return new Suchanfrage();
    }

    /**
     * Create an instance of {@link Suchergebnis }
     * 
     */
    public Suchergebnis createSuchergebnis() {
        return new Suchergebnis();
    }

    /**
     * Create an instance of {@link Code }
     * 
     */
    public Code createCode() {
        return new Code();
    }

}
