//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Die FIM-Stammdatenschemata werden auf allen föderalen Ebenen auf Basis von Gesetzen, Verordnungen sowie Verwaltungs- und Ausführungsvorschriften unter Anwendung des Redaktionsprozesses entwickelt. Stammdatenschemata sollen Allgemeingültigkeit besitzen.
 * 
 * <p>Java class for Stammdatenschema complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Stammdatenschema"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:xoev-de:fim:standard:xdatenfelder_2}AllgemeineAngaben"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hilfetext" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin" minOccurs="0"/&gt;
 *         &lt;element name="ableitungsmodifikationenStruktur" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.AbleitungsmodifikationenStruktur"/&gt;
 *         &lt;element name="ableitungsmodifikationenRepraesentation" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.AbleitungsmodifikationenRepraesentation"/&gt;
 *         &lt;element name="regel" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Regel" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="struktur" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Struktur" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Stammdatenschema", propOrder = {
    "hilfetext",
    "ableitungsmodifikationenStruktur",
    "ableitungsmodifikationenRepraesentation",
    "regel",
    "struktur"
})
public class Stammdatenschema
    extends AllgemeineAngaben
{

    protected String hilfetext;
    @XmlElement(required = true)
    protected CodeAbleitungsmodifikationenStruktur ableitungsmodifikationenStruktur;
    @XmlElement(required = true)
    protected CodeAbleitungsmodifikationenRepraesentation ableitungsmodifikationenRepraesentation;
    protected List<Regel> regel;
    protected List<Struktur> struktur;

    /**
     * Gets the value of the hilfetext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHilfetext() {
        return hilfetext;
    }

    /**
     * Sets the value of the hilfetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHilfetext(String value) {
        this.hilfetext = value;
    }

    /**
     * Gets the value of the ableitungsmodifikationenStruktur property.
     * 
     * @return
     *     possible object is
     *     {@link CodeAbleitungsmodifikationenStruktur }
     *     
     */
    public CodeAbleitungsmodifikationenStruktur getAbleitungsmodifikationenStruktur() {
        return ableitungsmodifikationenStruktur;
    }

    /**
     * Sets the value of the ableitungsmodifikationenStruktur property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeAbleitungsmodifikationenStruktur }
     *     
     */
    public void setAbleitungsmodifikationenStruktur(CodeAbleitungsmodifikationenStruktur value) {
        this.ableitungsmodifikationenStruktur = value;
    }

    /**
     * Gets the value of the ableitungsmodifikationenRepraesentation property.
     * 
     * @return
     *     possible object is
     *     {@link CodeAbleitungsmodifikationenRepraesentation }
     *     
     */
    public CodeAbleitungsmodifikationenRepraesentation getAbleitungsmodifikationenRepraesentation() {
        return ableitungsmodifikationenRepraesentation;
    }

    /**
     * Sets the value of the ableitungsmodifikationenRepraesentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeAbleitungsmodifikationenRepraesentation }
     *     
     */
    public void setAbleitungsmodifikationenRepraesentation(CodeAbleitungsmodifikationenRepraesentation value) {
        this.ableitungsmodifikationenRepraesentation = value;
    }

    /**
     * Gets the value of the regel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Regel }
     * 
     * 
     */
    public List<Regel> getRegel() {
        if (regel == null) {
            regel = new ArrayList<Regel>();
        }
        return this.regel;
    }

    /**
     * Gets the value of the struktur property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the struktur property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStruktur().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Struktur }
     * 
     * 
     */
    public List<Struktur> getStruktur() {
        if (struktur == null) {
            struktur = new ArrayList<Struktur>();
        }
        return this.struktur;
    }

}
