//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Suchfeld.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Suchfeld"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="beschreibung"/&gt;
 *     &lt;enumeration value="bezeichnungAusgabe"/&gt;
 *     &lt;enumeration value="bezeichnungEingabe"/&gt;
 *     &lt;enumeration value="bezug"/&gt;
 *     &lt;enumeration value="codelistenWerte"/&gt;
 *     &lt;enumeration value="definition"/&gt;
 *     &lt;enumeration value="hilfetext"/&gt;
 *     &lt;enumeration value="hilfetextAusgabe"/&gt;
 *     &lt;enumeration value="hilfetextEingabe"/&gt;
 *     &lt;enumeration value="id"/&gt;
 *     &lt;enumeration value="inhalt"/&gt;
 *     &lt;enumeration value="name"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Suchfeld")
@XmlEnum
public enum Suchfeld {

    @XmlEnumValue("beschreibung")
    BESCHREIBUNG("beschreibung"),
    @XmlEnumValue("bezeichnungAusgabe")
    BEZEICHNUNG_AUSGABE("bezeichnungAusgabe"),
    @XmlEnumValue("bezeichnungEingabe")
    BEZEICHNUNG_EINGABE("bezeichnungEingabe"),
    @XmlEnumValue("bezug")
    BEZUG("bezug"),
    @XmlEnumValue("codelistenWerte")
    CODELISTEN_WERTE("codelistenWerte"),
    @XmlEnumValue("definition")
    DEFINITION("definition"),
    @XmlEnumValue("hilfetext")
    HILFETEXT("hilfetext"),
    @XmlEnumValue("hilfetextAusgabe")
    HILFETEXT_AUSGABE("hilfetextAusgabe"),
    @XmlEnumValue("hilfetextEingabe")
    HILFETEXT_EINGABE("hilfetextEingabe"),
    @XmlEnumValue("id")
    ID("id"),
    @XmlEnumValue("inhalt")
    INHALT("inhalt"),
    @XmlEnumValue("name")
    NAME("name");
    private final String value;

    Suchfeld(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Suchfeld fromValue(String v) {
        for (Suchfeld c: Suchfeld.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
