//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.06 at 11:34:55 AM UTC 
//


package uni.jena.fim.xdatenfelder.v2.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Die Suchanfrage legt fest, wonach an welchen Stellen gesucht werden soll.
 * 
 * <p>Java class for Suchanfrage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Suchanfrage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="elementTyp" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.ElementTyp" maxOccurs="5"/&gt;
 *         &lt;element name="begriff" type="{http://xoev.de/latinchars/1_1/datatypes}String.Latin"/&gt;
 *         &lt;element name="felder" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.Suchfeld" maxOccurs="unbounded"/&gt;
 *         &lt;element name="status" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.Status" minOccurs="0"/&gt;
 *         &lt;element name="ableitungsmodifikationenStruktur" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.AbleitungsmodifikationenStruktur" minOccurs="0"/&gt;
 *         &lt;element name="ableitungsmodifikationenRepraesentation" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.AbleitungsmodifikationenRepraesentation" minOccurs="0"/&gt;
 *         &lt;element name="schemaelementart" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.Schemaelementart" minOccurs="0"/&gt;
 *         &lt;element name="feldart" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.Feldart" minOccurs="0"/&gt;
 *         &lt;element name="datentyp" type="{urn:xoev-de:fim:standard:xdatenfelder_2}Code.Datentyp" minOccurs="0"/&gt;
 *         &lt;element name="gueltigAbNach" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="gueltigAbVor" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="gueltigBisNach" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="gueltigBisVor" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="freigabedatumNach" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="freigabedatumVor" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="veroeffentlichungsdatumNach" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="veroeffentlichungsdatumVor" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Suchanfrage", propOrder = {
    "elementTyp",
    "begriff",
    "felder",
    "status",
    "ableitungsmodifikationenStruktur",
    "ableitungsmodifikationenRepraesentation",
    "schemaelementart",
    "feldart",
    "datentyp",
    "gueltigAbNach",
    "gueltigAbVor",
    "gueltigBisNach",
    "gueltigBisVor",
    "freigabedatumNach",
    "freigabedatumVor",
    "veroeffentlichungsdatumNach",
    "veroeffentlichungsdatumVor"
})
public class Suchanfrage {

    @XmlElement(required = true)
    protected List<CodeElementTyp> elementTyp;
    @XmlElement(required = true)
    protected String begriff;
    @XmlElement(required = true)
    protected List<CodeSuchfeld> felder;
    protected CodeStatus status;
    protected CodeAbleitungsmodifikationenStruktur ableitungsmodifikationenStruktur;
    protected CodeAbleitungsmodifikationenRepraesentation ableitungsmodifikationenRepraesentation;
    protected CodeSchemaelementart schemaelementart;
    protected CodeFeldart feldart;
    protected CodeDatentyp datentyp;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gueltigAbNach;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gueltigAbVor;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gueltigBisNach;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gueltigBisVor;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freigabedatumNach;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar freigabedatumVor;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar veroeffentlichungsdatumNach;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar veroeffentlichungsdatumVor;

    /**
     * Gets the value of the elementTyp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elementTyp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElementTyp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeElementTyp }
     * 
     * 
     */
    public List<CodeElementTyp> getElementTyp() {
        if (elementTyp == null) {
            elementTyp = new ArrayList<CodeElementTyp>();
        }
        return this.elementTyp;
    }

    /**
     * Gets the value of the begriff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBegriff() {
        return begriff;
    }

    /**
     * Sets the value of the begriff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBegriff(String value) {
        this.begriff = value;
    }

    /**
     * Gets the value of the felder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the felder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFelder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeSuchfeld }
     * 
     * 
     */
    public List<CodeSuchfeld> getFelder() {
        if (felder == null) {
            felder = new ArrayList<CodeSuchfeld>();
        }
        return this.felder;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link CodeStatus }
     *     
     */
    public CodeStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeStatus }
     *     
     */
    public void setStatus(CodeStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the ableitungsmodifikationenStruktur property.
     * 
     * @return
     *     possible object is
     *     {@link CodeAbleitungsmodifikationenStruktur }
     *     
     */
    public CodeAbleitungsmodifikationenStruktur getAbleitungsmodifikationenStruktur() {
        return ableitungsmodifikationenStruktur;
    }

    /**
     * Sets the value of the ableitungsmodifikationenStruktur property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeAbleitungsmodifikationenStruktur }
     *     
     */
    public void setAbleitungsmodifikationenStruktur(CodeAbleitungsmodifikationenStruktur value) {
        this.ableitungsmodifikationenStruktur = value;
    }

    /**
     * Gets the value of the ableitungsmodifikationenRepraesentation property.
     * 
     * @return
     *     possible object is
     *     {@link CodeAbleitungsmodifikationenRepraesentation }
     *     
     */
    public CodeAbleitungsmodifikationenRepraesentation getAbleitungsmodifikationenRepraesentation() {
        return ableitungsmodifikationenRepraesentation;
    }

    /**
     * Sets the value of the ableitungsmodifikationenRepraesentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeAbleitungsmodifikationenRepraesentation }
     *     
     */
    public void setAbleitungsmodifikationenRepraesentation(CodeAbleitungsmodifikationenRepraesentation value) {
        this.ableitungsmodifikationenRepraesentation = value;
    }

    /**
     * Gets the value of the schemaelementart property.
     * 
     * @return
     *     possible object is
     *     {@link CodeSchemaelementart }
     *     
     */
    public CodeSchemaelementart getSchemaelementart() {
        return schemaelementart;
    }

    /**
     * Sets the value of the schemaelementart property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeSchemaelementart }
     *     
     */
    public void setSchemaelementart(CodeSchemaelementart value) {
        this.schemaelementart = value;
    }

    /**
     * Gets the value of the feldart property.
     * 
     * @return
     *     possible object is
     *     {@link CodeFeldart }
     *     
     */
    public CodeFeldart getFeldart() {
        return feldart;
    }

    /**
     * Sets the value of the feldart property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeFeldart }
     *     
     */
    public void setFeldart(CodeFeldart value) {
        this.feldart = value;
    }

    /**
     * Gets the value of the datentyp property.
     * 
     * @return
     *     possible object is
     *     {@link CodeDatentyp }
     *     
     */
    public CodeDatentyp getDatentyp() {
        return datentyp;
    }

    /**
     * Sets the value of the datentyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeDatentyp }
     *     
     */
    public void setDatentyp(CodeDatentyp value) {
        this.datentyp = value;
    }

    /**
     * Gets the value of the gueltigAbNach property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGueltigAbNach() {
        return gueltigAbNach;
    }

    /**
     * Sets the value of the gueltigAbNach property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGueltigAbNach(XMLGregorianCalendar value) {
        this.gueltigAbNach = value;
    }

    /**
     * Gets the value of the gueltigAbVor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGueltigAbVor() {
        return gueltigAbVor;
    }

    /**
     * Sets the value of the gueltigAbVor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGueltigAbVor(XMLGregorianCalendar value) {
        this.gueltigAbVor = value;
    }

    /**
     * Gets the value of the gueltigBisNach property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGueltigBisNach() {
        return gueltigBisNach;
    }

    /**
     * Sets the value of the gueltigBisNach property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGueltigBisNach(XMLGregorianCalendar value) {
        this.gueltigBisNach = value;
    }

    /**
     * Gets the value of the gueltigBisVor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGueltigBisVor() {
        return gueltigBisVor;
    }

    /**
     * Sets the value of the gueltigBisVor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGueltigBisVor(XMLGregorianCalendar value) {
        this.gueltigBisVor = value;
    }

    /**
     * Gets the value of the freigabedatumNach property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreigabedatumNach() {
        return freigabedatumNach;
    }

    /**
     * Sets the value of the freigabedatumNach property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreigabedatumNach(XMLGregorianCalendar value) {
        this.freigabedatumNach = value;
    }

    /**
     * Gets the value of the freigabedatumVor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFreigabedatumVor() {
        return freigabedatumVor;
    }

    /**
     * Sets the value of the freigabedatumVor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFreigabedatumVor(XMLGregorianCalendar value) {
        this.freigabedatumVor = value;
    }

    /**
     * Gets the value of the veroeffentlichungsdatumNach property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVeroeffentlichungsdatumNach() {
        return veroeffentlichungsdatumNach;
    }

    /**
     * Sets the value of the veroeffentlichungsdatumNach property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVeroeffentlichungsdatumNach(XMLGregorianCalendar value) {
        this.veroeffentlichungsdatumNach = value;
    }

    /**
     * Gets the value of the veroeffentlichungsdatumVor property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVeroeffentlichungsdatumVor() {
        return veroeffentlichungsdatumVor;
    }

    /**
     * Sets the value of the veroeffentlichungsdatumVor property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVeroeffentlichungsdatumVor(XMLGregorianCalendar value) {
        this.veroeffentlichungsdatumVor = value;
    }

}
