//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.21 at 02:07:50 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uni.jena.bpmn.xsd;
